import * as THREE from 'three';
import {NeuralModel,REGIONS,MODEL_COUNT,COLUMNS,BIN} from './neural.mjs';
const $=id=>document.getElementById(id);
export class BrainPanel {
 constructor(engine){
  this.engine=engine;this.model=new NeuralModel();this.mode='spikes';this.selected='all';this.time=0;this.paint=0;this.visible=true;
  this.host=$('brainScene');this.scene=new THREE.Scene();this.root=new THREE.Group();this.scene.add(this.root);
  this.camera=new THREE.PerspectiveCamera(35,1,.1,30);this.camera.position.set(0,-.08,8);this.camera.lookAt(0,-.08,0);
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor(0,0);this.host.appendChild(this.renderer.domElement);
  this.clouds=[];this.surfaces=[];this.positions=[];this.seed=189;
  const dot=document.createElement('canvas');dot.width=dot.height=32;const dc=dot.getContext('2d'),grad=dc.createRadialGradient(16,16,0,16,16,16);grad.addColorStop(0,'#ffffff');grad.addColorStop(.25,'#ffffff');grad.addColorStop(1,'#ffffff00');dc.fillStyle=grad;dc.fillRect(0,0,32,32);this.sprite=new THREE.CanvasTexture(dot);
  // Broad central brain envelope, deliberately schematic rather than atlas meshes.
  for(const s of [-1,1])this.shell([s*.53,.27,-.12],[.70,.76,.40],0x3f8fb5,.12);
  for(let g=0;g<REGIONS.length;g++){
   const pts=[];for(let i=0;i<REGIONS[g].count;i++)this.positions.push(this.position(g,i,REGIONS[g].count));
   for(let i=0;i<Math.max(240,REGIONS[g].count*15);i++)pts.push(...this.position(g,i,Math.max(240,REGIONS[g].count*15)));
   const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pts,3));const material=new THREE.PointsMaterial({color:REGIONS[g].color,size:.044,map:this.sprite,transparent:true,opacity:.68,depthWrite:false,blending:THREE.AdditiveBlending});const cloud=new THREE.Points(geo,material);this.root.add(cloud);this.clouds.push(cloud);
  }
  for(const s of [-1,1]){this.shell([s*1.57,.08,0],[.61,.79,.36],0x479ccf,.13);this.shell([s*1.96,.07,.03],[.17,.68,.30],0x5496d4,.07);this.shell([s*.45,-.39,.28],[.27,.24,.23],0xda93bd,.05)}
  const nodeGeo=new THREE.BufferGeometry();nodeGeo.setAttribute('position',new THREE.Float32BufferAttribute(this.positions.flat(),3));nodeGeo.setAttribute('color',new THREE.Float32BufferAttribute(new Float32Array(MODEL_COUNT*3),3));this.nodes=new THREE.Points(nodeGeo,new THREE.PointsMaterial({size:.082,map:this.sprite,vertexColors:true,transparent:true,depthWrite:false,blending:THREE.AdditiveBlending}));this.root.add(this.nodes);
  // Sparse illustrative arborizations, not a claim of reconstructed connectivity.
  const segments=[];let offset=0;REGIONS.forEach((r,g)=>{for(let i=0;i<r.count;i+=3){const a=this.positions[offset+i],b=this.positions[offset+(i+7)%r.count];segments.push(...a,...b)}offset+=r.count});const lines=new THREE.BufferGeometry();lines.setAttribute('position',new THREE.Float32BufferAttribute(segments,3));this.root.add(new THREE.LineSegments(lines,new THREE.LineBasicMaterial({color:0x63aac4,transparent:true,opacity:.11})));
  const tether=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,-1.1,0),new THREE.Vector3(.55,-1.45,0),new THREE.Vector3(1.4,-1.45,0)]);const pathway=new THREE.Line(tether,new THREE.LineDashedMaterial({color:0x74bbae,dashSize:.045,gapSize:.06,transparent:true,opacity:.5}));pathway.computeLineDistances();this.root.add(pathway);
  const makeLabel=(label,x,y,size=.15)=>{const c=document.createElement('canvas');c.width=256;c.height=48;const ctx=c.getContext('2d');ctx.fillStyle='#9bbccc';ctx.font='20px monospace';ctx.textAlign='center';ctx.fillText(label,128,30);const sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));sprite.position.set(x,y,.6);sprite.scale.set(size*256/48,size,1);this.root.add(sprite)};
  makeLabel('OPTIC LOBE',-1.65,-.91,.12);makeLabel('OPTIC LOBE',1.65,-.91,.12);makeLabel('CENTRAL BRAIN',0,1.21,.12);makeLabel('DN',.26,-1.1,.1);makeLabel('T1',1.96,-1.25,.085);makeLabel('T2',1.96,-1.48,.085);makeLabel('T3',1.96,-1.7,.085);
  new ResizeObserver(()=>this.resize()).observe(this.host);this.resize();
  new IntersectionObserver(entries=>{this.visible=entries[0].isIntersecting},{rootMargin:'100px'}).observe(this.host);
  let drag=null;this.host.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];this.host.setPointerCapture(e.pointerId)});this.host.addEventListener('pointermove',e=>{if(!drag)return;this.root.rotation.y+=(e.clientX-drag[0])*.007;this.root.rotation.x=Math.max(-.7,Math.min(.7,this.root.rotation.x+(e.clientY-drag[1])*.005));drag=[e.clientX,e.clientY]});for(const event of ['pointerup','pointercancel'])this.host.addEventListener(event,()=>drag=null);
  $('brainFront').onclick=()=>this.root.rotation.set(0,0,0);$('liveSpikes').onclick=()=>this.setMode('spikes');$('cellColors').onclick=()=>this.setMode('cells');
  document.querySelectorAll('[data-region]').forEach(b=>b.onclick=()=>{this.selected=b.dataset.region;document.querySelectorAll('[data-region]').forEach(other=>{const active=other===b;other.classList.toggle('selected',active);other.setAttribute('aria-pressed',active)});$('regionDescription').textContent=this.selected==='all'?'Explore the paired visual regions, central brain and descending pathways. The ventral nerve cord sits in the body, shown here as a separate inset.':REGIONS.find(r=>r.id===this.selected).description});
  this.ctx=$('spikeRaster').getContext('2d');this.raster=document.createElement('canvas');this.raster.width=COLUMNS;this.raster.height=MODEL_COUNT;this.rctx=this.raster.getContext('2d');this.pixels=this.rctx.createImageData(COLUMNS,MODEL_COUNT);this.drawRaster();
 }
 random(){this.seed=(1664525*this.seed+1013904223)>>>0;return this.seed/4294967296}
 ellipsoid(cx,cy,cz,rx,ry,rz){const u=this.random()*2-1,a=this.random()*Math.PI*2,r=Math.cbrt(this.random()),q=Math.sqrt(1-u*u);return[cx+rx*r*q*Math.cos(a),cy+ry*r*u,cz+rz*r*q*Math.sin(a)]}
 position(g,i,count){const s=i<count/2?-1:1;
  if(g===0){const layer=i%4;return this.ellipsoid(s*(layer===0?1.98:layer===1?1.67:1.33),.08,layer===3?-.20:.02,layer===0?.12:layer===1?.38:.27,layer===0?.62:layer===1?.76:.55,.30)}
  if(g===1){if(i%3===0){const a=this.random()*Math.PI*2;return[Math.cos(a)*.21,-.03+Math.sin(a)*.20,.35+(this.random()-.5)*.08]}if(i%3===1)return this.ellipsoid(0,.30,.03,.47,.15,.12);return this.ellipsoid(0,.70,-.1,.62,.065,.10)}
  if(g===2){if(i%3===0)return this.ellipsoid(s*.56,.63,.0,.22,.18,.18);if(i%3===1)return this.ellipsoid(s*.42,.24,.23,.07,.33,.08);return this.ellipsoid(s*.23,.0,.30,.24,.08,.09)}
  if(g===3)return this.ellipsoid(s*.45,-.39,.28,.26,.23,.22);
  if(g===4)return this.ellipsoid(0,-.65,-.03,.43,.30,.29);
  if(g===5)return this.ellipsoid(s*.075,-1,.02,.035,.27,.055);
  const segment=i%3;return this.ellipsoid(1.58+s*.095,-1.22-segment*.23,0,.10,.10,.10);
 }
 shell(position,scale,color,opacity){const m=new THREE.Mesh(new THREE.SphereGeometry(1,32,20),new THREE.MeshBasicMaterial({color,transparent:true,opacity,depthWrite:false}));m.position.set(...position);m.scale.set(...scale);this.root.add(m);this.surfaces.push(m)}
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;if(!w||!h)return;this.camera.aspect=w/h;this.camera.position.z=Math.max(5.5,4.9/(2*Math.tan(35*Math.PI/360)*this.camera.aspect));this.camera.updateProjectionMatrix();this.renderer.setSize(w,h)}
 setMode(mode){this.mode=mode;document.querySelector('.activity-key').classList.toggle('cell-legend',mode==='cells');for(const [id,m] of [['liveSpikes','spikes'],['cellColors','cells']]){$(id).classList.toggle('selected',mode===m);$(id).setAttribute('aria-pressed',mode===m)}$('brainModeLabel').textContent=mode==='cells'?'Colors identify anatomical groups':'Recent model spikes'}
 reset(){this.model.reset();this.drawRaster()}
 drawRaster(){const image=this.pixels,data=image.data,model=this.model;let n=0;REGIONS.forEach((region,g)=>{const color=new THREE.Color(region.color);const rgb=[Math.round(color.r*255),Math.round(color.g*255),Math.round(color.b*255)];for(let j=0;j<region.count;j++,n++)for(let x=0;x<COLUMNS;x++){const src=(model.cursor+x)%COLUMNS,on=model.raster[src][n],k=(n*COLUMNS+x)*4;data[k]=on?Math.max(90,rgb[0]):11;data[k+1]=on?Math.max(150,rgb[1]):25;data[k+2]=on?Math.max(150,rgb[2]):36;data[k+3]=255}});this.rctx.putImageData(image,0,0);const c=this.ctx,canvas=$('spikeRaster'),w=Math.max(240,canvas.clientWidth),h=canvas.clientHeight,ratio=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(w*ratio)||canvas.height!==Math.round(h*ratio)){canvas.width=Math.round(w*ratio);canvas.height=Math.round(h*ratio)}c.setTransform(ratio,0,0,ratio,0,0);c.clearRect(0,0,w,h);c.imageSmoothingEnabled=false;const left=33,top=8,pw=w-left-8,ph=h-29;c.drawImage(this.raster,left,top,pw,ph);let y=top;c.font='9px monospace';c.textAlign='right';REGIONS.forEach(r=>{c.fillStyle=r.color;c.fillText(r.short,left-6,y+r.count/MODEL_COUNT*ph/2+3);c.strokeStyle='#44617855';c.beginPath();c.moveTo(left,y);c.lineTo(w-8,y);c.stroke();y+=r.count/MODEL_COUNT*ph});c.fillStyle='#839cae';c.textAlign='left';c.fillText('−3 s',left,h-6);c.textAlign='center';c.fillText('−2 s',left+pw/3,h-6);c.fillText('−1 s',left+pw*2/3,h-6);c.textAlign='right';c.fillText('now',w-8,h-6)}

 update(dt){this.time+=dt;this.model.step(dt,this.engine);this.paint+=dt;if(this.paint<.03)return;this.paint=0;const colors=this.nodes.geometry.attributes.color;const base=new THREE.Color(),hot=new THREE.Color('#f2ffc1');this.model.neurons.forEach((n,i)=>{const region=REGIONS[n.group],selected=this.selected==='all'||this.selected===region.id;base.set(this.mode==='cells'?region.color:'#3888c2');if(this.mode==='spikes')base.lerp(hot,n.glow);base.multiplyScalar(selected?.55+n.glow*1.5:.10);colors.setXYZ(i,base.r,base.g,base.b)});colors.needsUpdate=true;this.clouds.forEach((cloud,i)=>{const selected=this.selected==='all'||this.selected===REGIONS[i].id;cloud.material.color.set(this.mode==='cells'?REGIONS[i].color:'#3999d2');cloud.material.opacity=selected?.88:.07});if(this.visible)this.renderer.render(this.scene,this.camera);this.drawRaster();$('spikeCount').textContent=this.model.spikes;$('activeCount').textContent=this.model.active;$('modelPhase').textContent=!this.engine.running?'REST':this.engine.stall?'HOLD':this.engine.phase<.5?'LOWER':'PRESS';for(const name of ['press','lower','hold']){const value=this.model.readout[name];$(name+'Drive').value=value;$(name+'Value').textContent=value.toFixed(2)}}
}
