import {readFile,writeFile,mkdir,rename} from 'node:fs/promises';
import {join} from 'node:path';
export function chooseTarget(names,stats){return [...names].sort((a,b)=>{const score=n=>{const s=stats[n]||{tries:0,wins:0};return s.tries? s.wins/s.tries+Math.sqrt(2*Math.log(2+Object.values(stats).reduce((n,s)=>n+s.tries,0))/s.tries):Infinity};return score(b)-score(a)})[0]}
export class MinecraftService{
 constructor(directory='.flylab'){this.directory=directory;this.bot=null;this.status='disconnected';this.log=[];this.stats={};this.skills={};this.busy=false;this.writeQueue=Promise.resolve()}
 async init(){await mkdir(this.directory,{recursive:true});try{const s=JSON.parse(await readFile(join(this.directory,'minecraft.json'),'utf8'));this.stats=s.stats||{};this.skills=s.skills||{};this.log=s.log||[]}catch(e){if(e.code!=='ENOENT')throw e}return this}
 record(message){this.log.unshift({at:Date.now(),message});this.log=this.log.slice(0,60);const data=JSON.stringify({stats:this.stats,skills:this.skills,log:this.log});this.writeQueue=this.writeQueue.catch(()=>{}).then(async()=>{const p=join(this.directory,'minecraft.tmp');await writeFile(p,data);await rename(p,join(this.directory,'minecraft.json'))}).catch(()=>{this.status='Could not save Minecraft progress';});}
 view(){return {status:this.status,busy:this.busy,connected:!!this.bot?.entity,log:this.log,skills:this.skills,targets:this.stats,inventory:this.bot?.inventory?.items().map(i=>({name:i.name,count:i.count}))||[]}}
 async connect(port){if(!Number.isInteger(port)||port<1024||port>65535)throw Error('Enter the LAN port shown by Minecraft Java.');if(this.bot)throw Error('Disconnect the current Minecraft bot first.');const {default:mineflayer}=await import('mineflayer');const {default:pf}=await import('mineflayer-pathfinder');this.status='connecting';const bot=mineflayer.createBot({host:'127.0.0.1',port,username:'FlyLab',auth:'offline',hideErrors:true});this.bot=bot;bot.loadPlugin(pf.pathfinder);this.record(`Connecting FlyLab to local Java world on port ${port}.`);const timer=setTimeout(()=>{if(!bot.entity){this.record('Connection timed out. Check the LAN port and compatible Java version.');this.disconnect()}},20000);
  bot.once('spawn',()=>{clearTimeout(timer);const movements=new pf.Movements(bot);movements.canDig=false;movements.allow1by1towers=false;movements.allowParkour=false;bot.pathfinder.setMovements(movements);this.status='ready';this.record('Joined the world. Ready for a practice attempt.');});bot.on('error',e=>{this.status='connection error';this.record(`Connection failed (${e.code||'protocol error'}). Check the port, Java version and local server settings.`)});bot.on('kicked',()=>{this.record('Server refused the bot. A server requiring Microsoft authentication needs a separate bot account; no authentication bypass is attempted.');});bot.once('end',()=>{clearTimeout(timer);if(this.bot===bot){this.bot=null;this.status='disconnected';this.busy=false}});return this.view();
 }
 disconnect(){if(this.bot){this.bot.pathfinder?.setGoal(null);this.bot.stopDigging();this.bot.quit();this.bot=null}this.status='disconnected';this.busy=false;return this.view()}
 async practice(){const bot=this.bot;if(!bot?.entity||this.busy)throw Error('Connect to a world and wait for the current attempt.');this.busy=true;this.status='practicing';let action='observe';let timer;let target;let cancelled=false;const check=()=>{if(cancelled||this.bot!==bot)throw Error('Attempt cancelled')};
  try{await Promise.race([(async()=>{const count=name=>bot.inventory.items().filter(i=>i.name===name).reduce((s,i)=>s+i.count,0);const items=bot.inventory.items();
   if(count('crafting_table')>0){this.record('First curriculum completed: wood → planks → crafting table.');return}
   const planks=items.filter(i=>i.name.endsWith('_planks')).reduce((s,i)=>s+i.count,0);
   if(planks>=4){action='crafting_table';const recipe=bot.recipesFor(bot.registry.itemsByName.crafting_table.id,null,1,null)[0];if(!recipe)throw Error('No usable table recipe');await bot.craft(recipe,1,null);check();if(!count('crafting_table'))throw Error('Table not found in inventory');}
   else if(items.some(i=>i.name.endsWith('_log'))){action='planks';const log=items.find(i=>i.name.endsWith('_log'));const item=bot.registry.itemsByName[log.name.replace('_log','_planks')];const recipe=item&&bot.recipesFor(item.id,null,4,null)[0];if(!recipe)throw Error('No usable plank recipe');await bot.craft(recipe,1,null);check();if(bot.inventory.items().filter(i=>i.name.endsWith('_planks')).reduce((s,i)=>s+i.count,0)<=planks)throw Error('No new planks in inventory');}
   else{action='gather_wood';const blocks=bot.findBlocks({matching:block=>block.name.endsWith('_log'),maxDistance:24,count:40}).map(p=>bot.blockAt(p)).filter(Boolean);target=chooseTarget([...new Set(blocks.map(b=>b.name))],this.stats);if(!target)throw Error('No logs visible within 24 blocks; move the fly near a tree.');const block=blocks.filter(b=>b.name===target).sort((a,b)=>a.position.distanceTo(bot.entity.position)-b.position.distanceTo(bot.entity.position))[0];this.record(`Trying ${target}; selecting targets from past successes and exploration.`);const {default:pf}=await import('mineflayer-pathfinder');await bot.pathfinder.goto(new pf.goals.GoalNear(block.position.x,block.position.y,block.position.z,2));check();const before=count(target);await bot.dig(bot.blockAt(block.position));check();await bot.pathfinder.goto(new pf.goals.GoalNear(block.position.x,block.position.y,block.position.z,1));await new Promise(r=>setTimeout(r,1500));check();if(count(target)<=before)throw Error('Wood was broken but not collected');}
   check();if(target){const s=this.stats[target]??={tries:0,wins:0};s.tries++;s.wins++}this.skills[action]=(this.skills[action]||0)+1;this.record(`Success: ${action}. Verified from inventory.`);
  })(),new Promise((_,reject)=>timer=setTimeout(()=>{cancelled=true;bot.pathfinder.setGoal(null);bot.stopDigging();reject(Error('Attempt timed out after 40 seconds'))},40000))]);
  }catch(e){if(target){const s=this.stats[target]??={tries:0,wins:0};s.tries++}this.record(`Attempt failed: ${action}. ${e.message}`)}finally{cancelled=true;clearTimeout(timer);this.busy=false;if(this.bot===bot)this.status='ready'}return this.view();
 }
}
