import {mkdir,readFile,writeFile,rename} from 'node:fs/promises';
import {join} from 'node:path';
import {randomUUID,createHash} from 'node:crypto';
import {NoteLearner} from './research-learning.mjs';
export const TOPICS=['Quantum mechanics: superposition and measurement','Finance fundamentals: compounding, diversification and risk','Minecraft Java: gathering wood and crafting a first shelter','Machine learning: reinforcement learning and rewards','Statistics: probability and uncertainty','Astronomy: how stars form','Computer science: algorithms and complexity','Fruit-fly learning and memory'];
export class ResearchService{
 constructor({provider,directory='.flylab',now=()=>Date.now(),dailyLimit=12}={}){this.provider=provider;this.directory=directory;this.now=now;this.dailyLimit=dailyLimit;this.sessions=[];this.learner=new NoteLearner();this.usage={date:'',lessons:0};this.busy=false;this.writeQueue=Promise.resolve()}
 async init(){await mkdir(this.directory,{recursive:true});try{const data=JSON.parse(await readFile(join(this.directory,'research.json'),'utf8'));this.sessions=data.sessions||[];this.learner=new NoteLearner(data.learning);this.usage=data.usage||this.usage;for(const s of this.sessions)if(s.status==='researching'){s.status='paused';s.error='Research was interrupted. Resume the session to continue.'}}catch(e){if(e.code!=='ENOENT')throw Error('Research save could not be read; it has been preserved.')}return this}
 save(){const data=JSON.stringify({sessions:this.sessions,learning:this.learner.serialize(),usage:this.usage});const job=this.writeQueue.catch(()=>{}).then(async()=>{const temp=join(this.directory,'research.tmp');await writeFile(temp,data);await rename(temp,join(this.directory,'research.json'))});this.writeQueue=job;return job}
 view(){const today=new Date(this.now()).toISOString().slice(0,10);return {available:!!this.provider?.key,busy:this.busy,topics:TOPICS,sessions:this.sessions,learning:{cards:this.learner.cards.length,updates:this.learner.updates},budget:{used:this.usage.date===today?this.usage.lessons:0,limit:this.dailyLimit}}}
 async start({topic='',sessionKey}={}){if(typeof topic!=='string'||topic.length>180)throw Error('Topic must be at most 180 characters.');if(typeof sessionKey!=='string'||sessionKey.length>100)throw Error('Invalid study session.');const found=this.sessions.find(s=>s.sessionKey===sessionKey);if(found)return found;if(this.sessions.some(s=>['studying','researching','paused','error'].includes(s.status)))throw Error('Finish or stop the current research session first.');if(!this.provider?.key)throw Error('The dedicated FlyLab API key is not configured.');const s={id:randomUUID(),sessionKey,topic:topic.trim()||TOPICS[this.sessions.length%TOPICS.length],startedAt:this.now(),elapsed:0,duration:3600,status:'studying',lessons:[],error:null};this.sessions.unshift(s);this.sessions=this.sessions.slice(0,100);await this.save();return s}
 async progress(id,elapsed){const s=this.sessions.find(s=>s.id===id);if(!s)throw Error('Study session not found.');if(!Number.isFinite(elapsed)||elapsed<0)throw Error('Invalid study time.');if(!['complete','stopped'].includes(s.status))s.elapsed=Math.max(s.elapsed,Math.min(3600,elapsed));await this.save();return s}
 async stop(id){const s=this.sessions.find(s=>s.id===id);if(!s)throw Error('Study session not found.');s.status='stopped';await this.save();return s}
 async resume(id){const s=this.sessions.find(s=>s.id===id);if(!s||!['error','paused'].includes(s.status))throw Error('This session cannot be resumed.');s.status='studying';s.error=null;await this.save();return s}
 async work(){if(this.busy)return;const s=this.sessions.find(s=>s.status==='studying');if(!s)return;const due=Math.min(4,1+Math.floor(s.elapsed/900));if(s.lessons.length>=due){if(s.elapsed>=3600&&s.lessons.length===4){s.status='complete';s.finishedAt=this.now();await this.save()}return}
  const date=new Date(this.now()).toISOString().slice(0,10);if(this.usage.date!==date)this.usage={date,lessons:0};if(this.usage.lessons>=this.dailyLimit){s.status='paused';s.error='Daily research limit reached. Resume tomorrow; existing notes are saved.';await this.save();return}
  this.busy=true;this.usage.lessons++;s.status='researching';s.error=null;
  try{await this.save();const lesson=await this.provider.lesson(s.topic,s.lessons.length,s.lessons.flatMap(l=>l.notes.map(n=>n.concept)));if(s.status==='stopped')return;
   const cards=lesson.notes.map((n,i)=>({...n,id:createHash('sha256').update(s.topic.toLowerCase()+':'+n.concept.toLowerCase()).digest('hex').slice(0,24),sources:n.sourceNumbers.map(number=>lesson.sources[number-1])}));const before=this.learner.evaluate(cards);this.learner.train(cards);const after=this.learner.evaluate(cards);s.lessons.push({...lesson,at:this.now(),simMinute:s.lessons.length*15,before,after});s.status=s.elapsed>=3600&&s.lessons.length===4?'complete':'studying';if(s.status==='complete')s.finishedAt=this.now();
  }catch(error){if(s.status!=='stopped'){s.status='error';s.error=String(error.message).slice(0,300)}}finally{this.busy=false;await this.save()}
 }
}
