import test from 'node:test';
import assert from 'node:assert/strict';
import {ActivityCore} from './core.mjs';
import {skills} from './skills/index.mjs';
import {workoutProgress} from './workouts.mjs';
const fresh=()=>new ActivityCore(skills);
function finish(c,id){c.stats={energy:100,fatigue:0};assert.ok(c.start(id));const p=c.current.plan;c.advance(c.current.duration);return p}
test('strength cycles include hypertrophy, five by five and progressive overload',()=>{const c=fresh();const first=finish(c,'bench-press');const strength=finish(c,'bench-press');assert.equal(strength.sets,5);assert.equal(strength.reps,5);assert.ok(strength.weight>first.weight);finish(c,'bench-press');const next=finish(c,'bench-press');assert.equal(next.reps,first.reps);assert.equal(next.weight,first.weight+5);assert.equal(c.history[0].plan.weight,next.weight)});
test('strength sets stop at exact rep targets and include real rest and rack phases',()=>{const c=fresh();c.start('bench-press');const p=c.current.plan;assert.equal(workoutProgress(p,0).phase,'warmup');assert.equal(workoutProgress(p,p.warmup+1).phase,'unrack');assert.equal(workoutProgress(p,p.warmup+3+p.reps*p.repSeconds+1).phase,'rack');const rest=workoutProgress(p,p.warmup+6+p.reps*p.repSeconds+1);assert.equal(rest.phase,'rest');assert.equal(rest.reps,p.reps);assert.equal(workoutProgress(p,p.duration).reps,p.sets*p.reps)});
test('endurance targets increase after finishing, not after cancelling',()=>{for(const id of ['marathon','swimming','stairmaster']){const c=fresh(),first=finish(c,id);c.stats={energy:100,fatigue:0};c.start(id);assert.ok(c.current.plan.target>first.target);const goal=c.current.plan.target;c.advance(60);c.current=null;c.stats={energy:100,fatigue:0};c.start(id);assert.equal(c.current.plan.target,goal);assert.equal(c.workouts[id].progress,1)}});
test('fatigue causes a deload without advancing hard-workout targets',()=>{const c=fresh();finish(c,'marathon');c.stats={energy:60,fatigue:70};c.start('marathon');assert.equal(c.current.plan.deload,true);const p=c.workouts.marathon.progress;c.advance(c.current.duration);assert.equal(c.workouts.marathon.progress,p)});
test('mid-set reload preserves exact plan, rep count and next-session progression',()=>{const c=fresh();finish(c,'bench-press');c.stats={energy:100,fatigue:0};c.start('bench-press');c.advance(201);const b=fresh();assert.ok(b.restore(c.serialize()));assert.deepEqual(b.current,c.current);assert.deepEqual(b.workouts,c.workouts);assert.deepEqual(workoutProgress(b.current.plan,b.current.elapsed),workoutProgress(c.current.plan,c.current.elapsed));});
